// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFhgXJmRRE4b4qNZbAZbpNEioOrZ5YGyA',
    appId: '1:617004716774:web:ff42c4879d5983f53da127',
    messagingSenderId: '617004716774',
    projectId: 'final-ac01f',
    authDomain: 'final-ac01f.firebaseapp.com',
    storageBucket: 'final-ac01f.firebasestorage.app',
    measurementId: 'G-GC495DR30C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHFFKHWU06Tq3gNQ8b8t9eG21f6W4bMX4',
    appId: '1:617004716774:android:ffc6a170e99c2bdd3da127',
    messagingSenderId: '617004716774',
    projectId: 'final-ac01f',
    storageBucket: 'final-ac01f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcHzNIcUU47BaxlKCGe8zIsy2FDyW1H2k',
    appId: '1:617004716774:ios:cf92c7c2d6b8051b3da127',
    messagingSenderId: '617004716774',
    projectId: 'final-ac01f',
    storageBucket: 'final-ac01f.firebasestorage.app',
    iosBundleId: 'com.mahmoud1360.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcHzNIcUU47BaxlKCGe8zIsy2FDyW1H2k',
    appId: '1:617004716774:ios:7f6c5d37ea7c64ae3da127',
    messagingSenderId: '617004716774',
    projectId: 'final-ac01f',
    storageBucket: 'final-ac01f.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFhgXJmRRE4b4qNZbAZbpNEioOrZ5YGyA',
    appId: '1:617004716774:web:06bd6f97133a2bb83da127',
    messagingSenderId: '617004716774',
    projectId: 'final-ac01f',
    authDomain: 'final-ac01f.firebaseapp.com',
    storageBucket: 'final-ac01f.firebasestorage.app',
    measurementId: 'G-YG97S58D2Z',
  );

}